1단계 - REST API 및 테스트 리팩토링
next-step/jwp-jdbc pull request #133
Opened 2022-08-15 08:30 UTC by testrace

안녕하세요 리뷰어님 😃 
1단계 리뷰 요청 드립니다!

뼈대 코드가 워낙 잘 되어 있어서 쉽게 봤다가 꽤나 고생했습니다! 생각만큼 쉽지 않더라구요 😢  
스프링의 `@RequestBody` 를 흉내내어 만들까 하다가 PostData가 필요한 곳에만 적용할 수 있도록 구현해 봤습니다.

많은 피드백 부탁드립니다!

2022-08-16 05:09 UTC, yongdae requested changes
안녕하세요. 용주님!
라이브러리 구현 미션 첫단계를 잘 구현해주셨네요. 💯 

소소하지만 진행해주신 부분에 대해 몇 가지 의견을 남겨 놓았습니다.
다음 단계로 넘어가기보다는 이 내용은 여기서 마무리 짓고 가는게 좋을 것 같아
Request changes로 진행하겠습니다. 😄

2022-08-16 05:09 UTC, yongdae commented on README.md
> +  - [x] 회원수정 `PUT /api/users`
미션을 진행하기 전에 먼저 요구사항을 정리해주셨네요. 👍

2022-08-16 05:09 UTC, yongdae commented on src/test/java/core/mvc/JsonViewTest.java
> +        model.put("name", "pobi");
<img width="898" alt="스크린샷 2022-08-16 오후 1 26 02" src="https://user-images.githubusercontent.com/4317804/184797664-9a569932-8962-4401-9643-8b89115025a4.png">

한글 데이터도 테스트가 통과 될 수 있도록 이 힌트를 적용해보면 어떨까요? 🤔 

<img width="796" alt="스크린샷 2022-08-16 오후 1 25 28" src="https://user-images.githubusercontent.com/4317804/184797602-eff56ca0-40e2-4faa-9e6a-8b04ab8c4d5b.png">

2022-08-16 05:09 UTC, yongdae commented on src/test/java/core/mvc/JsonUtilsTest.java
> +    }
다양하게 테스트 케이스를 정의해서 만들어주셨네요. 👍 
JsonUtils를 믿고 사용 할 수 있겠어요!

2022-08-16 05:09 UTC, yongdae commented on src/main/java/core/mvc/JsonUtils.java
> +    public static String getParameter(final String jsonString, final String jsonKey) throws ObjectMapperException {
[gson 라이브러리](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/JsonElement.html)처럼 getAsString() 같은 이름을 사용해보면 어떨까요?

2022-08-16 05:09 UTC, yongdae commented on src/main/java/core/mvc/JsonView.java
> +        try (final PrintWriter writer = response.getWriter()) {
Try-with-resource를 활용해주셨네요. 👍

2022-08-16 05:09 UTC, yongdae commented on src/main/java/core/mvc/tobe/support/ModelArgumentResolver.java
>  public class ModelArgumentResolver implements ArgumentResolver {
이야기하셨던 `@RequestBody`를 미션에 적용시켜보면 어떨까요?
Json을 처리 할 수 있는 ArgumentResolver를 추가하는 것도 미션의 일부라고 생각해본다면 좋을 것 같아요. :)

2022-08-16 05:09 UTC, yongdae commented on src/main/java/next/controller/UserApiController.java
> +public class UserApiController {
요구 사항에 대응하는 컨트롤러를 구현해주셨네요. 💯

2022-08-16 05:09 UTC, yongdae commented on src/test/java/core/mvc/tobe/support/RequestParameterUtilsTest.java
> +class RequestParameterUtilsTest {
👍

2022-08-17 01:07 UTC, testrace commented on src/main/java/core/mvc/JsonUtils.java
> +    public static String getParameter(final String jsonString, final String jsonKey) throws ObjectMapperException {
메서드명을 조금 더 구체적으로 명시하는게 API 사용자에게 더 도움이 될 것 같네요!
(네이밍은 어렵네요 😢 )

2022-08-17 01:08 UTC, testrace commented on src/test/java/core/mvc/JsonViewTest.java
> +        model.put("name", "pobi");
APPLICATION_JSON_UTF8_VALUE 를 사용하고 싶었는데, Deprecated 되었더라구요!

JsonView의 역할에서는 ContentType을 'application/json' 으로 응답하는게 조금 더 중요하다 생각했습니다!
애플리케이션 전체를 보면 `CharacterEncodingFilter`가 존재하고 있어서 JsonView는 CharacterEncoding보다 ContentType에
집중하는게 좋지 않을까 생각했습니다 😃 

JsonView가 한글도 처리할 수 있는 것은 저도 좋다고 생각해서 APPLICATION_JSON_UTF8_VALUE 를 직접 정의해서
(스프링꺼는 deprecated.. 😢 ) 한글 데이터도 통과할 수 있도록 변경해 보겠습니다!

2022-08-17 01:10 UTC, testrace commented on src/main/java/core/mvc/tobe/support/ModelArgumentResolver.java
>  public class ModelArgumentResolver implements ArgumentResolver {
지난 미션(Controller 메소드 인자 맵핑)의 연장이라 생각하니 재밌을 것 같네요! 구현해 보겠습니다 😃

2022-08-17 10:04 UTC, testrace commented
안녕하세요 리뷰어님 😃 
피드백 주신 부분들을 적용해 봤습니다!

HttpServletRequest에서 PostData를 읽는 것 까지는 괜찮았는데, 두 번은 읽을 수가 없어서 파라미터가 여러개 인 경우 재활용하기 위해 
ThreadLocal을 활용했는데요! ThreadLocal에서 가장 중요한 remove() 메서드를 호출하는 시점을 ModelAndView#render 호출 이후에
호출하도록 했습니다. 
그러다 보니 ThreadLocal을 가진 객체의 위치가 좀 애매해졌는데요.. DispatcherServlet이 support 패키지에 의존하는 상황이 되었습니다.

ThreadLocal을 remove하는 시점과 ThreadLocal을 가진 객체를 어느 곳에서 관리는 하는 것이 좋을지 조금 애매하더라구요!
리뷰어님의 의견이 궁금합니다!

많은 피드백 부탁드립니다 (__)

2022-08-17 12:44 UTC, testrace commented
혹시 피드백 의도와 다르게 반영되었다면 힌트와 함께 RequestChange 부탁드립니다 😃

2022-08-17 16:42 UTC, yongdae approved these changes
ThreadLocal을 사용해서 `@RequestBody`를 구현해주셨네요. 👍 
피드백을 열심히 그리고 잘 반영해주셔서 감사합니다~

그럼 다음 단계로 넘어가도록 하겠습니다.
의견 주신 부분에 대해서 답변을 남겨 놓았으니 확인 부탁드릴께요.

수고하셨습니다. 🙇

2022-08-17 16:42 UTC, yongdae commented on src/main/java/core/mvc/tobe/support/RequestBodyArgumentResolver.java
> +public class RequestBodyArgumentResolver extends AbstractModelArgumentResolver {
ThreadLocal을 사용함으로써 생기는 부수 효과는 예측하기 힘든 문제를 발생시킨다고 생각해요.

AbstractModelArgumentResolver를 상속받지 않고 RequestBody에 대한 ArgumentResolver를 구현한다면
ThreadLocal을 사용하지 않아도 되지 않을까요? 🤔 

ThreadLocal을 활용해주신 건 멋지다고 생각합니다!

2022-08-17 16:42 UTC, yongdae commented on src/test/java/core/mvc/tobe/support/RequestBodyArgumentResolverTest.java
> +class RequestBodyArgumentResolverTest {
이번에도 RequestBodyArgumentResolver 검증을 꼼꼼하게 해주셨네요. 💯

2022-08-17 16:42 UTC, merged

2022-08-23 10:30 UTC, testrace commented on src/main/java/core/mvc/tobe/support/RequestBodyArgumentResolver.java
> +public class RequestBodyArgumentResolver extends AbstractModelArgumentResolver {
스프링에서 RequestBody 애너테이션을 하나의 메서드에서도 여러 파라미터에 지원이 가능하도록 하고 싶었습니다!
ThreadLocal에 대한 이해도가 많이 부족하여 부수 효과에 대해서는 인지를 못한 것 같아요 😢 
연습 차원에서 사용해 봤는데 테스트 코드에서는 통과를 본 것에 의미를 두고 더 공부가 필요할 것 같습니다.
피드백 감사드립니다 😄