2단계 - JDBC 라이브러리 구현
next-step/jwp-jdbc pull request #142
Opened 2022-08-22 15:47 UTC by ldonghee

안녕하세요 리뷰어님:)
2단계 리뷰 요청드립니다.
꼼꼼한 리뷰 부탁드립니다 👍👍👍

2022-08-23 00:55 UTC, kang-hyungu requested changes
동희님 몇가지 코멘트 남겼습니다.
수정해보시고 리뷰 재요청주세요.

2022-08-23 00:55 UTC, kang-hyungu commented on src/main/java/next/dao/UserDao.java
> +        JdbcTemplate jdbcTemplate = new JdbcTemplate();
JdbcTemplate은 상태를 갖지 않는 객체입니다.
싱글톤 패턴을 적용하면 매번 객체를 생성하지 않으니 더 나은 성능을 보여줄 수 있겠네요.

2022-08-23 00:55 UTC, kang-hyungu commented on src/main/java/next/service/UserService.java
> +public interface UserService {
서비스를 인터페이스로 만들 필요가 있을까요?

2022-08-23 00:55 UTC, kang-hyungu commented on src/main/java/next/service/UserServiceImpl.java
> +		DataBase.addUser(user);
직접 구현한 DAO를 사용해서 db에 저장해보면 어떨까요

2022-08-23 00:55 UTC, kang-hyungu commented on src/test/java/next/dao/UserDaoTest.java
> +    public void crud() {
이 메서드는 2가지 테스트를 한꺼번에 진행하고 있네요
insert와 update는 각각 테스트 케이스로 만드는게 어떨까요

2022-08-23 00:55 UTC, kang-hyungu commented on src/main/java/core/jdbc/support/exception/DataAccessException.java
> +	public DataAccessException() {
들여쓰기를 탭으로 작성한 코드와 공백을 사용한 코드가 섞여있네요.
들여쓰기는 탭 또는 공백 둘 중 하나로 통일시켜주세요.

2022-08-23 12:19 UTC, ldonghee commented on src/main/java/next/service/UserService.java
> +public interface UserService {
서비스 레이어에 대해 인터페이스를 생성하고 구현체를 만드는 습관 때문에 만들었습니다.
이 부분에 대해 지적해 주셔서 감사합니다:)
현재 단계에서 추상화하여 사용하는 방법은 맞지 않아보이고, 습관적인 부분에 대해 한번 생각해보게 되었네요 ㅎㅎ

2022-08-25 06:37 UTC, kang-hyungu approved these changes
동희님 피드백 반영 잘 해주셨습니다.
pr은 머지 처리할게요 다음 미션 진행해주세요.

2022-08-25 06:37 UTC, kang-hyungu commented on src/main/java/core/jdbc/support/template/JdbcTemplate.java
> +        return new JdbcTemplate();
메서드로 호출할때 보다는 객체를 덜 생성하겠지만... Dao마다 새로운 JdbcTemplate 객체를 생성하겠네요.
빈으로 만들거나 싱글톤 패턴을 적용하시는 걸 추천합니다.

2022-08-25 06:37 UTC, merged