4단계 리뷰 요청드립니다.
next-step/jwp-jdbc pull request #159
Opened 2022-08-29 14:39 UTC by itdar

안녕하세요 성주님!
인터셉터 구현은 생각없이 스프링인터셉터를 implements 만 했다가... 새로 구현을 해야 할 것 같아서 스프링을 참고해서 구현했습니다 ㅎㅎ;
path 패턴 파싱은 코드를 그대로 따왔고.. 나머지는 대략적인 구조만 가져와서 새로 구현해보았습니다.
이번에도 리뷰 감사합니다!!!!

- DispatcherServlet 에서 InterceptorRegistry 에 사용할 Interceptor 등록 (이 때, 원하는 컨트롤러의 path 입력)
- 요청 받아서 service() 시에, 인터셉터 각각 메서드의 실행 시점에 맞게 실행
  - 실행 시 유효한 컨트롤러 path 에 대하여 인터셉터 실행

2022-08-30 14:28 UTC, liquidjoo requested changes
4단계 미션 정말 잘구현해주셨어요 👍 
몇 가지 코멘트 남겼는데요~ 확인하고 다시 요청해주세요 🙇

2022-08-30 14:28 UTC, liquidjoo commented on src/main/java/core/mvc/DispatcherServlet.java
> +                interceptorRegistry.applyPostHandler(req, resp, maybeHandler.get(), mav);
컨트롤러의 전 후 를 다룰 수 있게 표현한 점이 인상 깊네요!

2022-08-30 14:28 UTC, liquidjoo commented on src/main/java/core/mvc/DispatcherServlet.java
> +            interceptorRegistry.triggerAfterCompletion(req, resp, maybeHandler.get());
마지막 마무리 까지 👍

2022-08-30 14:28 UTC, liquidjoo commented on src/main/java/core/web/interceptor/HandlerInterceptor.java
> +}
Spring 에서 지원하는 HandlerInterceptor 인터페이스를 가져오셨군요!!
해당 인터페이스를 참고하는 것도 좋지만~ 어떠한 이유로 default 메서드를 가지게 되었는지~
추가적인 메서드가 필요할 때 어떻게 확장해 볼 것인지도 고려해보면 좋을 것 같아요~

2022-08-30 14:28 UTC, liquidjoo commented on src/main/java/core/web/interceptor/InterceptorRegistration.java
> +        private final PathPattern pathPattern;
해당 상태 값이 초기화만하고 사용 되고 있지 않는 것 같아요~
불필요한 코드는 제거해보는 것이 어떨까요?

2022-08-30 14:28 UTC, liquidjoo commented on src/main/java/core/web/interceptor/InterceptorRegistry.java
> +    }
해당 메서드가 사용 되고 있는 곳이 없어보여요~

2022-08-31 11:54 UTC, itdar commented on src/main/java/core/mvc/DispatcherServlet.java
> +                interceptorRegistry.applyPostHandler(req, resp, maybeHandler.get(), mav);
감사합니다!! 스프링 인터셉터 적용되는 부분의 구조를 유사하게 하긴 했는데..
실제론 더 복잡해서 이정도가 최선이었습니다..ㅠㅠ

2022-08-31 11:55 UTC, itdar commented on src/main/java/core/web/interceptor/InterceptorRegistration.java
> +        private final PathPattern pathPattern;
엇 옙 제거해보겠습니다!!

2022-08-31 11:55 UTC, itdar commented on src/main/java/core/web/interceptor/InterceptorRegistry.java
> +    }
옙 같이 제거해보겠습니다!!

2022-08-31 11:59 UTC, itdar commented on src/main/java/core/web/interceptor/HandlerInterceptor.java
> +}
넵 하위 클래스들이 불필요한 메서드 오버라이딩을 피하도록 (+ 이전 버전 인터페이스와 달라지는 것들에 대한 컴파일타임 안전장치)
으로 알고 있습니다! 제가 사용할 때는 ExecutionTimeCheckHandlerInterceptor 에서 안쓰는 postHandle() 은 불필요한 오버라이딩이라서 제거해보았습니다!! 짚어주셔서 감사합니다!!!

2022-09-01 13:56 UTC, liquidjoo approved these changes
4단계 피드백 반영 정말 좋았어요 👍 
형진님과 리뷰를 하는 시간이 즐거웠네요
저의 리뷰가 도움이 되었길 바래요 🙏 
너무 고생하셨습니다
궁금한 사항이 있으면 언제든 DM 주세요~

2022-09-01 13:56 UTC, liquidjoo commented on src/main/java/core/web/interceptor/InterceptorRegistration.java
> +        this.includePatterns = PatternAdapter.initPatterns(patterns);
피드백 반영 👍

2022-09-01 13:56 UTC, liquidjoo commented on src/main/java/core/web/interceptor/InterceptorRegistration.java
> +                .map(PatternAdapter::new)
코드가 한결 가벼워 지네요~

2022-09-01 13:56 UTC, merged

2022-09-01 15:54 UTC, itdar commented
> 4단계 피드백 반영 정말 좋았어요 👍 형진님과 리뷰를 하는 시간이 즐거웠네요 저의 리뷰가 도움이 되었길 바래요 🙏 너무 고생하셨습니다 궁금한 사항이 있으면 언제든 DM 주세요~

 안녕하세요 성주님!!
벌써 마지막 단계 리뷰가 끝났네요 ㅠㅠ
저도 성주님이 리뷰도 잘해주시고 칭찬도 해주시고 해서 힘내서 열심히 할 수 있었습니다.
감사합니다!! 질문 있으면 종종 질문 드리겠습니다 ㅎㅎ;
수고하셨습니다~!! @liquidjoo