Step3 JDBC 라이브러리 구현(힌트)
next-step/jwp-jdbc pull request #169
Opened 2022-09-03 13:15 UTC by fistkim101

step2 에서 피드백 주신 부분을 적용하다보니, 변경점이 꽤 많아서
연습삼아 깔끔하게 다시 만들어보는게 나을 것 같아서 ~V2 네이밍으로 아예 다 새로 구현했습니다.

잘 부탁드립니다~.

2022-09-04 07:33 UTC, yongdae requested changes
이전 단계에서 드린 의견을 잘 포함해서 미션을 진행해주셨네요. 👍 
힌트를 조금 더 적용해보는게 좋을 것 같아서 ReqeustChanges로 진행하도록 하겠습니다.
의견 드린 부분 확인하시고 다시 리뷰 요청 부탁드릴께요~ 🔥

2022-09-04 07:33 UTC, yongdae commented on src/main/java/core/jdbc/JdbcTemplateV2.java
> +public class JdbcTemplateV2 {
새로운 버전을 구현해주셨네요. 💯 

JdbcTemplate, JdbcTemplateV2 이렇게 두개가 있으니 헷갈리는 부분이 있는 것 같아요.
기존의 JdbcTemplate은 지우고 JdbcTemplateV2를 JdbcTemplate로 사용하는게 어떨까요?

이 의견 반영 여부는 리뷰이님이 원하시는데로 하시면 됩니다. :)

2022-09-04 07:33 UTC, yongdae commented on src/main/java/core/jdbc/JdbcTemplateV2.java
> +            this.setParameters(preparedStatement, parameters);
<img width="1063" alt="스크린샷 2022-09-04 오후 4 17 12" src="https://user-images.githubusercontent.com/4317804/188302126-41a2ffba-b176-4a37-a9ce-70686ae6e330.png">
미션 힌트 중에 PreparedStatementSetter를 적용해보면 좋겠어요.
SQL의 매개변수를 설정 부분을 분리 할 수 있다면 조금 더 유연성을 가진 JdbcTemplate이 되지 않을까요? 🤔

2022-09-04 07:33 UTC, yongdae commented on src/test/java/core/jdbc/JdbcTemplateV2Test.java
> +public class JdbcTemplateV2Test {
의견 드린 부분을 잘 반영해서 만들어주셨네요.
CRUD뿐만 아니라 예외 테스트까지 꼼꼼하게 만들어주셔서 좋은 것 같습니다. 💯

2022-09-04 07:33 UTC, yongdae commented on src/main/java/core/jdbc/JdbcTemplateV2.java
> +public class JdbcTemplateV2 {
학습의 차원에서 최종적으로는 힌트의 설계대로 JdbcTemplate를 정의해보면 어떨까요?

<img width="970" alt="스크린샷 2022-09-04 오후 4 25 32" src="https://user-images.githubusercontent.com/4317804/188302461-fb3c8d41-df9c-4abe-8853-95cc2c3146b4.png">

2022-09-04 07:33 UTC, yongdae commented on src/main/java/core/jdbc/RowMapperV2.java
> +public interface RowMapperV2<T> {
인터페이스인 RowMapper는 테스트를 할 수 있는 방법이 없을까요? 🤔

2022-09-07 06:07 UTC, fistkim101 commented
피드백 주신 사항 반영해보았습니다. 감사합니다 !!

2022-09-07 14:26 UTC, yongdae approved these changes
피드백 드린 부분을 잘 반영해주셨네요. 👍 
그럼 다음 단계로 넘어가도록 하겠습니다.

진행해주신 내용에 대해 추가로 의견 드린 부분은 다음 단계에서 반영 부탁드릴께요.
수고하셨습니다. 🙇

2022-09-07 14:26 UTC, yongdae commented on src/main/java/core/jdbc/JdbcTemplate.java
>  public class JdbcTemplate {
힌트를 잘 미션에 반영해주셨네요. 💯

2022-09-07 14:26 UTC, yongdae commented on src/main/java/core/jdbc/JdbcTemplate.java
> +    private PreparedStatementSetter getPreparedStatementSetter(Object... parameters) {
PreparedStatementSetter 구현체를 만들어보면 어떨까요?

    public class DefaultPreparedStatementSetter implements PreparedStatementSetter<PreparedStatement>  {
      ...
    }
PreparedStatementSetter에 제네릭을 적용하고 java.sql 패키지의 PreparedStatement를 사용한다면
이런 방식으로도 구현해볼 수 있을 것 같아요.

2022-09-07 14:26 UTC, yongdae commented on src/main/java/core/jdbc/ObjectRowMapper.java
> +public class ObjectRowMapper<T> implements RowMapper<T> {
공용의 RowMapper를 잘 구현해주셨네요. 👍 

    class UserRowMapper implements RowMapper<User> 

User를 타입으로 하는 RowMapper를 만드는건 어떻게 생각하시나요? 🤔

2022-09-07 14:26 UTC, yongdae commented on src/test/java/core/jdbc/ObjectRowMapperTest.java
> +class ObjectRowMapperTest {
💯

2022-09-07 14:26 UTC, merged

2022-09-08 00:51 UTC, fistkim101 commented on src/main/java/core/jdbc/ObjectRowMapper.java
> +public class ObjectRowMapper<T> implements RowMapper<T> {
공용으로 쓸 경우에 이를 사용하는 곳에서
    private RowMapper<User> rowMapper() {
        return new ObjectRowMapper<>(User.class);
    }

이렇게 메소드 한 줄로 표현이 가능하지만, 타입별로 RowMapper를 만들 경우에
entity 마다 Mapper class 를 만들어줘야 할 것으로 보여서 공용으로 만드는게 좋다고 판단했었습니다.

이번 미션의 user entity 외에 더 이상 entity가 늘어나지 않는다는 전제로 보면 UserRowMapper 를 만드는 것도 좋을 것 같다고 생각했습니다. 제가 리뷰어님 질문의 의도를 제대로 파악을 한건지 잘 모르겠네요!

2022-09-08 01:53 UTC, yongdae commented on src/main/java/core/jdbc/ObjectRowMapper.java
> +public class ObjectRowMapper<T> implements RowMapper<T> {
네 질문에 답변을 잘 남겨주셨네요.
리뷰이님의 설계 의도를 알고 싶었습니다!

한가지 더 추가로 질문을 드리고 싶은 부분이 있는데요.
의견을 주신 것처럼 `공용`은 좋다고 생각합니다. 그런 의미에서 ObjectRowMapper는 엔티티가 늘어날수록 활용도가 좋습니다. 👍 

다만 `공용`이라는 의미는 누구나 쓰기 때문에 `언제든 변경이 일어 날 수 있는 요소`로 생각합니다.

예를 들어 특정 Entity가 가진 특별한 값을 위해 특정한 기능을 수행해야 하는 상황이 발생한다면
우리는 쉽게 `공용`이 가진 이점을 포기 할 수 없어 `공용`에 특정 Entity만을 위한 코드를 추가하게 됩니다.

이 부분에 대해서는 어떻게 생각하시나요? 🤔

2022-09-08 03:15 UTC, fistkim101 commented on src/main/java/core/jdbc/ObjectRowMapper.java
> +public class ObjectRowMapper<T> implements RowMapper<T> {
제가 거기까진 생각을 해보지 못했네요 ㅎㅎ 리뷰어님 말씀을 보고 제가 생각을 해보니, 특정 entity 의 row를 매핑하다가 특정 컬럼에 대해서 형변환을 하거나 계산을 하는등의 처리가 필요한 경우 공용 객체가 특정한 엔티티를 위한 코드로 더렵혀질 일이 있을 것 같기도 합니다. 그리고 개인적으로 생각해볼때 이러한 경우는 충분히 있을 것 같습니다.

결국 리뷰어님 말씀대로 RowMapper 객체 내에서 '특정 Entity가 가진 특별한 값을 위해 특정한 기능을 수행해야 하는 상황이 발생' 할 일이 많을 가능성이 큰 경우 entity 별로 따로 구현해주는 것이 좋을 것 같습니다! 다음번 스텝에서 이를 고려해서 UserRowMapper를 구현해보겠습니다.

2022-09-08 03:26 UTC, fistkim101 commented on src/main/java/core/jdbc/JdbcTemplate.java
> +    private PreparedStatementSetter getPreparedStatementSetter(Object... parameters) {
리뷰어님 이 부분 피드백 해주신 것 관련하여 제가 포인트를 잘 파악하지 못하는 것 같습니다 ㅎㅎ 현재 코드상에서

private PreparedStatementSetter getPreparedStatementSetter(Object... parameters) {
        return preparedStatement -> {
            int index = 0;
            for (Object parameter : parameters) {
                preparedStatement.setObject(index + 1, parameter);
                index++;
            }
        };
    }
    
와 같이 메소드 하나로 간단하게(?) 사용중인 것 같다고 생각했었는데요~!

1. 혹시 현재의 방향과 달리 PreparedStatementSetter를 구현체로 만드는 것의 이점이 있다면 혹시 어떤 것이 있을지
2. 구현체로 만든다면 여기에 제네릭을 사용하는 이유나 방식이 어떤 것이 있을지

질문을 드려도 될까요? 특히 2번의 경우 PreparedStatementSetter 가 다양한 클래스가 들어오는 것에 대해 특별히 고려를 해주지 않아도 기능 처리가 가능한 것 같아서 더욱 제네릭을 말씀해주신 부분의 구현 방식을 제가 잘 생각하질 못하겠습니다 ㅠ.ㅠ

2022-09-08 12:45 UTC, yongdae commented on src/main/java/core/jdbc/JdbcTemplate.java
> +    private PreparedStatementSetter getPreparedStatementSetter(Object... parameters) {
1. JdbcTemplate에서 값을 설정하는(PreparedStatement) 부분을 분리 할 수 있습니다. 다르게 말하면 책임을 분리해서 정의하기 때문에 책임에 따른 응집도를 높이고 재사용성이 쉬워집니다.

2.  제네릭을 통해 PreparedStatementSetter를 정의한다면 유연하게 타입을 정의해서 활용 할 수 있습니다. [개방 폐쇄 원칙](https://ko.wikipedia.org/wiki/%EA%B0%9C%EB%B0%A9-%ED%8F%90%EC%87%84_%EC%9B%90%EC%B9%99)을 적용한다면 우리는 더 좋은 설계를 할 수 있다고 생각해요. 이야기하신 것처럼 `다양한 클래스가 들어오는 것에 대해 특별히 고려를 해주지 않아도` 됩니다. 그리고 제네릭을 학습하는 차원에서도 괜찮지 않을까요? 

코드 예시 (이런 예시를 원하시는건지 맞는지 잘 모르겠네요.)

    public interface PreparedStatementSetter<T> { ... }
    public class DefaultPreparedStatementSetter implements PreparedStatementSetter<PreparedStatement> { ... }

2022-09-08 23:09 UTC, fistkim101 commented on src/main/java/core/jdbc/JdbcTemplate.java
> +    private PreparedStatementSetter getPreparedStatementSetter(Object... parameters) {
상세한 설명 감사합니다! 피드백 참고하여 리팩토링 해보겠습니다 :)