4단계 - Interceptor 구현
next-step/jwp-jdbc pull request #176
Opened 2022-09-05 12:38 UTC by ldonghee

안녕하세요 리뷰어님
이번 미션의 마지막 단계네요.
마지막까지 잘 부탁드립니다.👍

2022-09-06 07:19 UTC, kang-hyungu requested changes
동희님, 간단한 코멘트 하나 남겼습니다.
수정해보시고 리뷰 재요청주세요.

2022-09-06 07:19 UTC, kang-hyungu commented on src/main/java/next/interceptor/ExecutionTimerInterceptor.java
> +		HttpSession session = request.getSession();
session을 쓰면 세션 상태를 서버에 저장할테니 session 대신에 request.setAttribute()를 활용해보는게 어떨까요?

2022-09-20 04:54 UTC, ldonghee commented on src/main/java/next/interceptor/ExecutionTimerInterceptor.java
> +		HttpSession session = request.getSession();
넵 피드백 감사합니다 ㅎㅎ 수정후 재요청 드리겠습니다:)

2022-09-22 11:33 UTC, kang-hyungu approved these changes
동희님 피드백 반영 잘 해주셨습니다.
pr은 머지 처리할게요. 수고하셨습니다!

2022-09-22 11:33 UTC, merged