[Step3] 3단계 - JDBC 라이브러리 구현(힌트)
next-step/jwp-jdbc pull request #32
Opened 2019-08-22 05:27 UTC by jaeyeonling

안녕하세요

피드백 반영하였습니다.

피드백 내용이 워낙 좋아 반영하고 나니 추가로 작업할 내용이 안보이네요.

부족한 부분 피드백 주시면 반영하도록 하겠습니다.

감사합니다!

2019-08-22 05:36 UTC, jaeyeonling commented
추가로 4단계 진행 예정입니다!

2019-08-22 09:39 UTC, kingbbode requested changes
만들어진 class에 비해 테스트가 부족한 것 같아요!
새로 만들어진 class 들을 위한 단위 테스트를 만들어보시는 것은 어떨까요?
피드백도 남겼습니다 :)

2019-08-22 09:39 UTC, kingbbode commented on src/main/java/next/dao/UserDao.java
> +                .orElseThrow();
객체가 있고 없고에 따라 처리되는 행위는 '서비스 레이어'에게 맡기는 것이 좋지 않을까요 :)

2019-08-22 09:39 UTC, kingbbode commented on src/main/java/next/jdbc/OrderIndexSupplier.java
> +        while (!parameters.isEmpty()) {
단순 for문이면 충분하지 않을까요?

2019-08-22 09:39 UTC, kingbbode commented on src/main/java/next/dao/UserDao.java
>          jdbcTemplate.execute(sql, supplier);
아래와 같은 사용성을 제공해주면 사용자가 Supplier 를 알 필요가 없어지겠네요 :)
```
execute(sql, user.getUserId(), user.getPassword(), user.getName(),
                user.getEmail())
```

2019-08-23 10:42 UTC, jaeyeonling commented
안녕하세요

주신 피드백 반영하였습니다~

확인해주시면 감사하겠습니다!

2019-08-23 12:39 UTC, kingbbode approved these changes
깔끔하네요 👍 
3단계까지 고생 많으셨어요 :)
Advanced 미션 구현하실지, 이번 단계에서 마무리하실지 DM 보내주세요!

2019-08-23 12:39 UTC, kingbbode commented on src/main/java/next/jdbc/TypeMapper.java
> +public class TypeMapper<T> implements ResultMapper<T> {
요쪽도 테스트되었으면 좋았을텐데 아쉽네요 :)

2019-08-23 12:39 UTC, kingbbode commented on src/test/java/next/jdbc/JdbcTemplateTest.java
> +        defaultUser = new User("jaeyeonling", "P@ssw0!d",
테스트의 조건 값으로 할당되는 값은 Before 단계보다는 테스트에 직접 할당하는게 가독과 유연성 측면에서 더 좋습니다 :)
계속 중복된다면 메서드로 제공을 하는 것도 방법이겠네요,

2019-08-23 12:39 UTC, merged